/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutoController;
import javax.swing.JOptionPane;
import Model.Produto;
import Utils.Validador;

/**
 *
 * @author Administrador
 */
public class CadastrarProduto extends javax.swing.JFrame {
    
    String modoTela = "cadastrar";
    int codigoProduto = 0;
    /**
     * Creates new form CadastroProduto
     */
    public CadastrarProduto() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public CadastrarProduto(int idProduto) {
        initComponents();
        setLocationRelativeTo(null);
        modoTela = "alterar";
        codigoProduto= idProduto;
        preencheCampos(idProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblEstoqueMinimo = new javax.swing.JLabel();
        lblEstoqueAtual = new javax.swing.JLabel();
        lblCodigoBarras = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtEstoqueMinimo = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtEstoqueAtual = new javax.swing.JTextField();
        txtCodigoBarras = new javax.swing.JTextField();
        btnCadastrar1 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblErros = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNome.setText("Nome");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescricao.setText("Descrição");

        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCategoria.setText("Categoria");

        lblCor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCor.setText("Cor");

        lblPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPreco.setText("Preço");

        lblEstoqueMinimo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEstoqueMinimo.setText("Estoque Mínimo");

        lblEstoqueAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEstoqueAtual.setText("Estoque Atual");

        lblCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodigoBarras.setText("Codigo de Barras");

        lblImagem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblImagem.setText("Imagem");

        txtEstoqueMinimo.setText("0");
        txtEstoqueMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueMinimoActionPerformed(evt);
            }
        });

        txtPreco.setText("0");
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        txtEstoqueAtual.setText("0");

        btnCadastrar1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCadastrar1.setText("SALVAR");
        btnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar1ActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblErros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnLimparCampos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimparCampos.setText("LIMPAR CAMPOS");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoBarras)
                            .addComponent(lblNome)
                            .addComponent(lblDescricao)
                            .addComponent(lblCategoria)
                            .addComponent(lblPreco)
                            .addComponent(lblCor)
                            .addComponent(lblEstoqueMinimo)
                            .addComponent(lblImagem)
                            .addComponent(lblEstoqueAtual)
                            .addComponent(btnCadastrar1))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstoqueMinimo)
                                    .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                                    .addComponent(txtCor)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnLimparCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(btnVoltar)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEstoqueAtual)
                    .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEstoqueMinimo)
                    .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoBarras))
                .addGap(36, 36, 36)
                .addComponent(lblImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar1)
                    .addComponent(btnVoltar)
                    .addComponent(btnLimparCampos))
                .addGap(39, 39, 39)
                .addComponent(lblErros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    private void preencheCampos(int idProduto)
    {   
        ProdutoController controller = new ProdutoController();
        String[] produtos = new String[11];
        produtos = controller.consultaCodigoAlterar(idProduto);
        txtNome.setText(produtos[1]);
        txtCategoria.setText(produtos[3]);
        txtCodigoBarras.setText(produtos[8]);
        txtCor.setText(produtos[5]);
        txtDescricao.setText(produtos[2]);
        txtEstoqueAtual.setText(produtos[6]);
        txtEstoqueMinimo.setText(produtos[7]);
        txtPreco.setText(produtos[4]);
    }
    
    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        Validador validador = new Validador();
        ProdutoController controller = new ProdutoController();
        int codigoBarras, estoqueAtual, estoqueMinimo;
        double preco;
            
        validador.isNull(txtNome, lblErros);
        validador.isNull(txtDescricao, lblErros);
        validador.isNull(txtCategoria, lblErros);
        validador.isNull(txtCor, lblErros);
        validador.isNull(txtCategoria, lblErros);
        
        
        try {
            codigoBarras = Integer.parseInt(txtCodigoBarras.getText());
            estoqueAtual = Integer.parseInt(txtEstoqueAtual.getText());
            estoqueMinimo = Integer.parseInt(txtEstoqueMinimo.getText());
            preco = Double.parseDouble(txtPreco.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos de valor!.");
            return;
        }
        
        if (validador.isNull(txtNome, lblErros) || validador.isNull(txtDescricao, lblErros) || validador.isNull(txtCategoria, lblErros)
            || validador.isNull(txtCor, lblErros) || validador.isNull(txtCategoria, lblErros)) {
            
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        } else {
            String nome = txtNome.getText();
            String descricao = txtDescricao.getText();
            String departamento = txtCategoria.getText();
            String cor = txtCor.getText();
            
            if (modoTela == "alterar") {
                boolean alteracao = controller.alteraProduto(nome, descricao, codigoBarras, cor, departamento, estoqueAtual, estoqueMinimo, preco, "www.google.com", codigoProduto);
                if (alteracao == true) {
                    JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");
                    limparCampos();
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Houve um erro ao alterar o produto.");
                }
            } else {
                boolean insercao = controller.cadastraProduto(nome, descricao, codigoBarras, cor, departamento, estoqueAtual, estoqueMinimo, preco, "www.google.com");
        
                if (insercao == true) {
                    JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Houve um erro ao cadastrar o produto.");
                }
            }            
        }
    }//GEN-LAST:event_btnCadastrar1ActionPerformed

    private void txtEstoqueMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueMinimoActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed
       
    public void limparCampos ()
    {
        txtNome.setText("");
        txtDescricao.setText("");
        txtCategoria.setText("");
        txtCor.setText("");
        txtCodigoBarras.setText("");
        txtEstoqueAtual.setText("");
        txtEstoqueMinimo.setText("");
        txtPreco.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblEstoqueAtual;
    private javax.swing.JLabel lblEstoqueMinimo;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueAtual;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
