/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.VendaController;
import Utils.Validador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayrto
 */
public class FinalizarVenda extends javax.swing.JFrame {
    
    Validador validador = new Validador();
    DefaultTableModel tmPayments = new DefaultTableModel();
    /**
     * Creates new form FinalizarVenda
     */
    public FinalizarVenda() {
        initComponents();
        txtVendedor.setEditable(false);
        txtCliente.setEditable(false);
        txtValorPago.setEditable(false);
        txtTroco.setEditable(false);
        txtValorTotal.setEditable(false);
        txtMetodo.setEditable(false);
        tmPayments.addColumn("Método");
        tmPayments.addColumn("Valor");
        tblPagamentos.setModel(tmPayments);
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroPedido = new javax.swing.JTextField();
        txtVendedor = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        btnDinheiro = new javax.swing.JButton();
        btnDébito = new javax.swing.JButton();
        btnCredito = new javax.swing.JButton();
        btnBoleto = new javax.swing.JButton();
        btnCheque = new javax.swing.JButton();
        btnOutros = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValoraPagar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtParcelas = new javax.swing.JTextField();
        txtMetodo = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtValorTotal = new javax.swing.JTextField();
        txtValorPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnFinalizarVenda = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnConsultaPedido = new javax.swing.JButton();
        lblErros = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPagamentos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmNovaVenda = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenuItem();
        jmRelatório = new javax.swing.JMenuItem();
        jmEstoque = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Venda");

        txtNumeroPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumeroPedido.setPreferredSize(new java.awt.Dimension(0, 23));

        txtVendedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtVendedor.setPreferredSize(new java.awt.Dimension(0, 23));

        txtCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCliente.setPreferredSize(new java.awt.Dimension(0, 23));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nº Pedido");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Cliente");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Vendedor");

        painel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Métodos de Pagamento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        btnDinheiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro.png"))); // NOI18N
        btnDinheiro.setText("Dinheiro");
        btnDinheiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDinheiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDinheiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDinheiro.setPreferredSize(new java.awt.Dimension(73, 60));
        btnDinheiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDinheiroActionPerformed(evt);
            }
        });

        btnDébito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDébito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/card.png"))); // NOI18N
        btnDébito.setText("Débito");
        btnDébito.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDébito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDébito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDébito.setPreferredSize(new java.awt.Dimension(73, 60));
        btnDébito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDébito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDébitoActionPerformed(evt);
            }
        });

        btnCredito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/card.png"))); // NOI18N
        btnCredito.setText("Crédito");
        btnCredito.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCredito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCredito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCredito.setPreferredSize(new java.awt.Dimension(73, 60));
        btnCredito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });

        btnBoleto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/boleto.png"))); // NOI18N
        btnBoleto.setText("Boleto");
        btnBoleto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBoleto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBoleto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBoleto.setPreferredSize(new java.awt.Dimension(73, 60));
        btnBoleto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletoActionPerformed(evt);
            }
        });

        btnCheque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/card.png"))); // NOI18N
        btnCheque.setText("Cheque");
        btnCheque.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCheque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCheque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCheque.setPreferredSize(new java.awt.Dimension(73, 60));
        btnCheque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequeActionPerformed(evt);
            }
        });

        btnOutros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOutros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnOutros.setText("Outros");
        btnOutros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOutros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOutros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOutros.setPreferredSize(new java.awt.Dimension(73, 60));
        btnOutros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(btnDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDébito, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDébito, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Valor a ser pago");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Método");

        txtValoraPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValoraPagar.setPreferredSize(new java.awt.Dimension(0, 23));
        txtValoraPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValoraPagarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Parcelas");

        txtParcelas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtParcelas.setPreferredSize(new java.awt.Dimension(0, 23));

        txtMetodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMetodo.setPreferredSize(new java.awt.Dimension(0, 23));

        btnPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValoraPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(100, Short.MAX_VALUE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(84, 84, 84)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtValoraPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(360, Short.MAX_VALUE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtMetodo, txtParcelas, txtValoraPagar});

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtValorTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValorTotal.setText("0");
        txtValorTotal.setBorder(null);
        txtValorTotal.setPreferredSize(new java.awt.Dimension(0, 23));

        txtValorPago.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValorPago.setText("0");
        txtValorPago.setBorder(null);
        txtValorPago.setPreferredSize(new java.awt.Dimension(0, 23));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Valor pago");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Troco");

        txtTroco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTroco.setText("0");
        txtTroco.setBorder(null);
        txtTroco.setPreferredSize(new java.awt.Dimension(0, 23));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Valot total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFinalizarVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFinalizarVenda.setText("<html>FINALIZAR<br/>A VENDA</html>");
        btnFinalizarVenda.setToolTipText("");
        btnFinalizarVenda.setName(""); // NOI18N
        btnFinalizarVenda.setPreferredSize(new java.awt.Dimension(73, 60));
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        btnCancelarVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarVenda.setText("<html>CANCELAR<br/>A VENDA</html>");
        btnCancelarVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarVenda.setPreferredSize(new java.awt.Dimension(73, 60));
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Pagamentos");

        btnConsultaPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConsultaPedido.setText("Consultar");
        btnConsultaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPedidoActionPerformed(evt);
            }
        });

        lblErros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblPagamentos);

        jMenu1.setText("Opções");

        jmNovaVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmNovaVenda.setText("Nova Venda");
        jMenu1.add(jmNovaVenda);

        jmCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmCadastro.setText("Cadastro");
        jMenu1.add(jmCadastro);

        jmRelatório.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jmRelatório.setText("Relatório");
        jMenu1.add(jmRelatório);

        jmEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jmEstoque.setText("Estoque");
        jMenu1.add(jmEstoque);

        jmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jmSair.setText("Sair");
        jMenu1.add(jmSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErros, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsultaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)))
                                .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarVenda, btnFinalizarVenda});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErros)
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCliente, txtNumeroPedido, txtVendedor});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelarVenda, btnFinalizarVenda});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        boolean sucesso = VendaController.finalizaCompra(Integer.parseInt(txtNumeroPedido.getText()), tblPagamentos);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Pedido finalizado com sucesso!.");
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível finalizar o pedido.");
        }
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void btnDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDinheiroActionPerformed
        txtMetodo.setText("Dinheiro");
        txtParcelas.setEditable(false);
    }//GEN-LAST:event_btnDinheiroActionPerformed

    private void btnDébitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDébitoActionPerformed
        txtMetodo.setText("Debito");
        txtParcelas.setEditable(false);
    }//GEN-LAST:event_btnDébitoActionPerformed

    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed
        txtMetodo.setText("Credito");
        txtParcelas.setEditable(true);
    }//GEN-LAST:event_btnCreditoActionPerformed

    private void btnBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletoActionPerformed
        txtMetodo.setText("Boleto");
        txtParcelas.setEditable(false);
    }//GEN-LAST:event_btnBoletoActionPerformed

    private void btnChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequeActionPerformed
        txtMetodo.setText("Cheque");
        txtParcelas.setEditable(false);
    }//GEN-LAST:event_btnChequeActionPerformed

    private void btnOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrosActionPerformed
        txtMetodo.setText("Outros");
        txtParcelas.setEditable(false);
    }//GEN-LAST:event_btnOutrosActionPerformed

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja mesmo cancelar a venda? de ID","Cancelar", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            boolean resultado = VendaController.cancelaCompra(Integer.parseInt(txtNumeroPedido.getText()));
            if (resultado) {
                JOptionPane.showMessageDialog(this, "Venda cancelada com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível cancelar a venda solicitada.");
            }
        }
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    private void btnConsultaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPedidoActionPerformed
        if(!(validador.ValidarNumero(txtNumeroPedido, lblErros) == "ok")){
            int numero = Integer.parseInt(txtNumeroPedido.getText());
            boolean retorno = VendaController.consultaPedido(numero, txtVendedor, txtCliente, txtValorTotal);
            if(!retorno){
                JOptionPane.showMessageDialog(this, "Não foi possível encontrar o pedido solicitado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Insira um número de pedido válido.");
        }
        
    }//GEN-LAST:event_btnConsultaPedidoActionPerformed

    private void txtValoraPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValoraPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValoraPagarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        boolean success = false;
        if (!(Validador.isNull(txtMetodo, lblErros)) && !(validador.ValidarNumero(txtValoraPagar, lblErros) == "ok")){
            if(txtMetodo.getText().contentEquals("Credito")) {
                if (!(validador.isNull(txtParcelas, lblErros))){
                    String parcelas = "Credito "+txtParcelas.getText()+"x";
                    tmPayments.addRow(new Object[]{parcelas, txtValoraPagar.getText()});
                    success = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Para cartão de crédito, informe as parcelas.");
                    return;
                }
            } else {
               tmPayments.addRow(new Object[]{txtMetodo.getText(), txtValoraPagar.getText()});
               success = true;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma forma de pagamento e informe o valor!");
        }
        
        if (success == true) {
            double valorPago = Double.parseDouble(txtValorPago.getText()) + Double.parseDouble(txtValoraPagar.getText());
            if( valorPago > Double.parseDouble(txtValorTotal.getText())) {
                double troco = valorPago - Double.parseDouble(txtValorTotal.getText());
                txtTroco.setText(Double.toString(troco));
            }
            txtValorPago.setText(Double.toString(valorPago));
            limpaCampos();
        }
        
        
    }//GEN-LAST:event_btnPagarActionPerformed
    
     public void limpaCampos()
     {
         txtMetodo.setText("");
         txtParcelas.setText("");
         txtValoraPagar.setText("");
         txtParcelas.setEditable(false);
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoleto;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnCheque;
    private javax.swing.JButton btnConsultaPedido;
    private javax.swing.JButton btnCredito;
    private javax.swing.JButton btnDinheiro;
    private javax.swing.JButton btnDébito;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnOutros;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem jmCadastro;
    private javax.swing.JMenuItem jmEstoque;
    private javax.swing.JMenuItem jmNovaVenda;
    private javax.swing.JMenuItem jmRelatório;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JLabel lblErros;
    private javax.swing.JPanel painel;
    private javax.swing.JTable tblPagamentos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtMetodo;
    private javax.swing.JTextField txtNumeroPedido;
    private javax.swing.JTextField txtParcelas;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValoraPagar;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
