/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author castro
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnNovaVenda = new javax.swing.JMenu();
        btnProduto = new javax.swing.JMenu();
        btnClientes = new javax.swing.JMenu();
        miConsultaCli = new javax.swing.JMenuItem();
        miAddCli = new javax.swing.JMenuItem();
        btnFuncionario = new javax.swing.JMenu();
        miConsultaFunc = new javax.swing.JMenuItem();
        miAddFunc = new javax.swing.JMenuItem();
        btnRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnNovaVenda.setText("Nova Venda");
        jMenuBar1.add(btnNovaVenda);

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnProduto.setText("Produtos");
        jMenuBar1.add(btnProduto);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnClientes.setText("Clientes");

        miConsultaCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miConsultaCli.setText("Consultar");
        miConsultaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCliActionPerformed(evt);
            }
        });
        btnClientes.add(miConsultaCli);

        miAddCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miAddCli.setText("Adicionar");
        miAddCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddCliActionPerformed(evt);
            }
        });
        btnClientes.add(miAddCli);

        jMenuBar1.add(btnClientes);

        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnFuncionario.setText("Funcionários");

        miConsultaFunc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miConsultaFunc.setText("Consultar");
        miConsultaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaFuncActionPerformed(evt);
            }
        });
        btnFuncionario.add(miConsultaFunc);

        miAddFunc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miAddFunc.setText("Adicionar");
        miAddFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddFuncActionPerformed(evt);
            }
        });
        btnFuncionario.add(miAddFunc);

        jMenuBar1.add(btnFuncionario);

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro.png"))); // NOI18N
        btnRelatorio.setText("Relatórios");
        jMenuBar1.add(btnRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miConsultaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCliActionPerformed
        
        AdminClientes tela = new AdminClientes();
        tela.setVisible(true);
        
    }//GEN-LAST:event_miConsultaCliActionPerformed

    private void miAddCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddCliActionPerformed
        
        CadastrarCliente tela = new CadastrarCliente();
        tela.setVisible(true);
        
    }//GEN-LAST:event_miAddCliActionPerformed

    private void miConsultaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaFuncActionPerformed
        
        AdminFuncionario tela = new AdminFuncionario();
        tela.setVisible(true);
        
    }//GEN-LAST:event_miConsultaFuncActionPerformed

    private void miAddFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddFuncActionPerformed
        
        CadastrarFuncionario tela = new CadastrarFuncionario();
        tela.setVisible(true);
        
    }//GEN-LAST:event_miAddFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnClientes;
    private javax.swing.JMenu btnFuncionario;
    private javax.swing.JMenu btnNovaVenda;
    private javax.swing.JMenu btnProduto;
    private javax.swing.JMenu btnRelatorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miAddCli;
    private javax.swing.JMenuItem miAddFunc;
    private javax.swing.JMenuItem miConsultaCli;
    private javax.swing.JMenuItem miConsultaFunc;
    // End of variables declaration//GEN-END:variables
}
